# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
#  option: value

# output configuration options
output:
  # See the dedicated "output" documentation section.
#  option: value

# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
#  option: value

linters:
  # See the dedicated "linters" documentation section.
  disable-all: true
#  disable:
#    - goanalysis_metalinter
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
#    - metalinter
    - module
    - performance
#    - sql
    - style
    - test
    - unused

issues:
  # See the dedicated "issues" documentation section.
#  option: value

severity:
  # See the dedicated "severity" documentation section.
#  option: value
