# Make sure to check the documentation at https://goreleaser.com
dist: ./target
before:
  hooks:
    - go generate ./...
    - go mod download

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

builds:
  - id: cli
    binary: gastly
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - >-
        -s -w
        -X github.com/blancsoft/gastly/cmd.version={{.Version}}
        -X github.com/blancsoft/gastly/cmd.commit={{.Commit}}
        -X github.com/blancsoft/gastly/cmd.commitDate={{.CommitDate}}
        -X github.com/gzuidhof/tygo/cmd.target={{.Env.GOOS}}

  - id: wasm
    binary: wasm/gastly
    main: ./cmd/wasm
    env:
      - CGO_ENABLED=0
    goos:
      - js
    goarch:
      - wasm

  - id: lambda
    binary: lambda/main
    main: ./cmd/lambda
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goarm: "6"
        gomips: hardfloat

archives:
  - id: lambda
    format: zip
    builds:
      - lambda
    strip_parent_binary_folder: true

nfpms:
  - id: gastly
    package_name: gastly
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Chuma Umenze
    homepage: https://github.com/blancsoft/gastly
    maintainer: Chuma Umenze <chuma@blancsoft.com>
    description: Go abstract syntax tree navigator
    license: Unlicensed
    formats:
      - deb
      - rpm

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - '^docs:'
#      - '^test:'
